# .streamlit/secrets.toml
dbbl_api_key = "48673298c840c12a1646b737c83e5e5e"
OPENAI_API_KEY = "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"
